name: ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'provider'
      - 'sdk'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'provider'
      - 'sdk'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.goversion }}
          cache-dependency-path: provider/go.sum

      - name: Install GoLangCI Lint
        run: |
          # binary will be $(go env GOPATH)/bin/golangci-lint
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.3
          golangci-lint --version

      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.12.0
        with:
          repo: pulumi/pulumictl

      - name: Build
        run: make build

      - name: Lint
        run: make lint
        shell: bash

    strategy:
      fail-fast: true
      matrix:
        goversion:
          - 1.20.x